export const supportedSkillIconIds = new Set([
  'ableton',
  'activitypub',
  'actix',
  'adonis',
  'ae',
  'aiscript',
  'ai',
  'alpinejs',
  'anaconda',
  'androidstudio',
  'angular',
  'ansible',
  'apollo',
  'apple',
  'appwrite',
  'arch',
  'arduino',
  'astro',
  'atom',
  'au',
  'autocad',
  'aws',
  'azul',
  'azure',
  'babel',
  'bash',
  'bevy',
  'bitbucket',
  'blender',
  'bootstrap',
  'bsd',
  'bun',
  'c',
  'cassandra',
  'clion',
  'clojure',
  'cloudflare',
  'cmake',
  'codepen',
  'coffeescript',
  'cpp',
  'crystal',
  'cs',
  'css',
  'cypress',
  'd3',
  'dart',
  'debian',
  'deno',
  'devto',
  'django',
  'docker',
  'dotnet',
  'dynamodb',
  'eclipse',
  'elasticsearch',
  'electron',
  'elixir',
  'elysia',
  'emacs',
  'ember',
  'emotion',
  'express',
  'fastapi',
  'fediverse',
  'figma',
  'firebase',
  'flask',
  'flutter',
  'forth',
  'fortran',
  'gamemakerstudio',
  'gatsby',
  'gcp',
  'gherkin',
  'git',
  'github',
  'githubactions',
  'gitlab',
  'gmail',
  'go',
  'godot',
  'gradle',
  'grafana',
  'graphql',
  'gtk',
  'gulp',
  'haskell',
  'haxe',
  'haxeflixel',
  'heroku',
  'hibernate',
  'html',
  'htmx',
  'idea',
  'instagram',
  'ipfs',
  'java',
  'jenkins',
  'jest',
  'jquery',
  'js',
  'kafka',
  'kali',
  'kotlin',
  'ktor',
  'kubernetes',
  'laravel',
  'latex',
  'less',
  'linkedin',
  'linux',
  'lit',
  'lua',
  'mastodon',
  'materialui',
  'matlab',
  'maven',
  'md',
  'mint',
  'misskey',
  'mongodb',
  'mysql',
  'neovim',
  'nestjs',
  'netlify',
  'nextjs',
  'nginx',
  'nim',
  'nix',
  'nodejs',
  'notion',
  'npm',
  'nuxtjs',
  'obsidian',
  'ocaml',
  'octave',
  'opencv',
  'openshift',
  'openstack',
  'p5js',
  'perl',
  'php',
  'phpstorm',
  'pinia',
  'pkl',
  'plan9',
  'planetscale',
  'pnpm',
  'postgres',
  'postman',
  'powershell',
  'pr',
  'prisma',
  'processing',
  'prometheus',
  'ps',
  'pug',
  'py',
  'pycharm',
  'pytorch',
  'qt',
  'r',
  'rabbitmq',
  'rails',
  'raspberrypi',
  'react',
  'reactivex',
  'redis',
  'redux',
  'redhat',
  'regex',
  'remix',
  'replit',
  'rider',
  'robloxstudio',
  'rocket',
  'rollupjs',
  'ros',
  'ruby',
  'rust',
  'sass',
  'scala',
  'selenium',
  'sentry',
  'sequelize',
  'sketchup',
  'sklearn',
  'solidjs',
  'solidity',
  'spring',
  'sqlite',
  'stackoverflow',
  'styledcomponents',
  'sublime',
  'supabase',
  'svelte',
  'svg',
  'swift',
  'symfony',
  'tailwind',
  'tauri',
  'tensorflow',
  'terraform',
  'threejs',
  'ts',
  'twitter',
  'ubuntu',
  'unity',
  'unreal',
  'v',
  'vala',
  'vercel',
  'vim',
  'visualstudio',
  'vite',
  'vitest',
  'vscode',
  'vscodium',
  'vue',
  'vuetify',
  'wasm',
  'webflow',
  'webpack',
  'webstorm',
  'windicss',
  'windows',
  'wordpress',
  'workers',
  'xd',
  'yarn',
  'yew',
  'zig',
])

const skillIconAliases: Record<string, string> = {
  '.net': 'dotnet',
  'adobe illustrator': 'ai',
  'adobe photoshop': 'ps',
  'android studio': 'androidstudio',
  angularjs: 'angular',
  autocad: 'autocad',
  csharp: 'cs',
  'c sharp': 'cs',
  'c#': 'cs',
  'c++': 'cpp',
  css3: 'css',
  dockerfile: 'docker',
  expressjs: 'express',
  'express.js': 'express',
  fastapi: 'fastapi',
  githubactions: 'githubactions',
  'github actions': 'githubactions',
  golang: 'go',
  html5: 'html',
  javascript: 'js',
  kotlin: 'kotlin',
  kubernetes: 'kubernetes',
  next: 'nextjs',
  'next.js': 'nextjs',
  node: 'nodejs',
  'node.js': 'nodejs',
  photoshop: 'ps',
  postgresql: 'postgres',
  python: 'py',
  reactjs: 'react',
  'react.js': 'react',
  scikit: 'sklearn',
  'scikit-learn': 'sklearn',
  sklearn: 'sklearn',
  sqlite3: 'sqlite',
  tailwindcss: 'tailwind',
  'tailwind css': 'tailwind',
  typescript: 'ts',
  unrealengine: 'unreal',
  'unreal engine': 'unreal',
  vuejs: 'vue',
  'vue.js': 'vue',
}

export function normalizeSkillIconId(icon: string) {
  const normalizedIcon = icon.toLowerCase().trim()
  return skillIconAliases[normalizedIcon] || normalizedIcon
}

export function isSupportedSkillIcon(icon: string) {
  return supportedSkillIconIds.has(normalizeSkillIconId(icon))
}

export function getSkillIconUrl(icon: string) {
  return `https://skillicons.dev/icons?i=${normalizeSkillIconId(icon)}`
}
